config/routes.rb
Rails.application.routes.draw do
  root  "tasks#index"
  resources :tasks 
  resources :users, only:  %i[new create show]
  resources :sessions, only: %i[new create destroy]

  namespace :admin do
    resources :users
    resources :tags
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: {message: "is required"}
    has_many :taggings, dependent: :destroy
    has_many :tasks, through: :taggings, source: :task
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
    before_action :set_tag, only: [:edit,:update, :destroy]
    before_action :check_admin
    def index
        @tags = Tag.all
    end
    def new
        @tag = Tag.new
    end
    def create
        @tag = Tag.new(tag_params)
        if @tag.save
            redirect_to admin_tags_path, notice: "New Tag create with success"
        else  
            render :new
        end
    end
    def edit
    end
    def update
        if @tag.update(tag_params)
            redirect_to admin_tags_path, notice: "Tag update with success"
        else
            render :edit
        end
    end
    def destroy
        @tag.destroy
        redirect_to admin_tags_path, notice: "Tag delete with success"
    end
    private
    def tag_params
        params.require(:tag).permit(:name)
    end
    def set_tag
        @tag = Tag.find(params[:id])
    end
    def check_admin
        unless current_user.admin
            redirect_to tasks_path, notice: "Your are not authorized to see this page"
        end
    end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
    def choose_new_or_edit
        if action_name == 'new'
            admin_tags_path
        elsif action_name == 'edit'
            admin_tag_path    
        end
    end
end

app/views/admin/tags/_form.html.erb
<div class="container">
    <div class="row justify-content-center align-content-center">
        <div class= "col-lg-5 col-md-8 col-sm-12 col-xl-4">
            <div class="card p-3 mb-3 bg-white" >
                <div class="card-header pl-4 pb-0 text-center" style="border: none; background-color:white;">
                    <%= image_tag "myTask.png", height: 80, width: 80 %>         
                </div>
                <div class="card-body">
                    <%= form_with(model: @tag, local: true, url: choose_new_or_edit) do |form| %>
                        <div class="form-group">
                            <%= form.text_field :name, class: "form-control bg-light small", required: true, placeholder: "Tag name" %>
                        </div>
                        
                        <div class="row justify-content-center mb-3 mt-4">
                            <div class="col-md-12 text-center">
                                 <% if action_name == "new"%>
                                    <%= form.submit "Create Tag", class:"btn btn-primary font-weight-bold pl-5 pr-5" %>
                                <% else %>
                                    <%= form.submit "Edit Tag", class:"btn btn-primary font-weight-bold pl-5 pr-5" %>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                </div>  
            </div>
        </div> 
    </div>
</div>
<div class="d-block text-center">
    <p><%= link_to "Back", admin_users_path, class: "btn btn-primary text-white" %></p>
</div>

app/views/admin/tags/edit.html.erb
<% if @tag.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show pt-2 pb-2 text-center">
        <% @tag.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>
<div class="container-fluid pt-3 pb-2" id='intro'>
    <div class="row justify-content-center align-content-center text-center">
        <div class="col-md-5">
            <h1>Admin Interface</h1>
            <p class="mt-3 mb-4"> Edit an new Tag </p>                        
        </div>
    </div>
</div>
<%= render 'form' %>

app/views/admin/tags/index.html.erb
<div class="container-fluid pt-5 pb-2" id='intro'>
    <div class="row justify-content-center align-content-center text-center">
        <div class="col-md-5">
            <h1>Admin Interface</h1>
            <p class="mt-4 mb-4"> Here you manage all tags of Tasks. You can add, edit and delete them.</p>  
            <p><%= link_to "Go back to user page", admin_users_path, class: "btn btn-primary text-white" %></p>                      
        </div>
    </div>
</div>


<div class="container-fluid mt-2 mb-3">
    <div class="row justify-content-center align-content-center">
        <div class="col-md-5">
            <p><%= link_to "New Tag", new_admin_tag_path, class: "btn btn-primary new_btn text-white" %></p>
            <table class="table table-sm">
                <thead>
                    <tr>
                    <th scope="col">Name</th>                  
                    </tr>
                </thead>
                <tbody>
                    <% if @tags.count > 0%>
                        <% @tags.each do |tag| %>
                            <tr>
                                <th scope="row" class="task_row"><%=tag.name %></th>
                                <td><%= link_to 'Edit' , edit_admin_tag_path(tag.id), class: "edit-link"  %></td>
                                <td><%= link_to 'Delete' ,admin_tag_path(tag.id), method: :delete , data: { confirm: 'Are you sure to delete this tag'}, class:"delete-link" %></td>
                            </tr>
                        <%end%>       
                    <%end%>   
                </tbody>
            </table>
            <% if @tags.count == 0 %>                   
                <p class="text-center font-weight-bold"> Nothing to show yet.</p>
                <p class="text-center"> If you don't have any tag, please create your first tag</p>
                <div class="d-block text-center">
                    <p><%= link_to "Create First Tag", new_admin_tag_path, class: "btn btn-primary text-white" %></p>
                </div>
            <%end%>  
                                   
        </div>
    </div>
</div>


app/views/admin/tags/new.html.erb
<% if @tag.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show pt-2 pb-2 text-center">
        <% @tag.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>
<div class="container-fluid pt-3 pb-2" id='intro'>
    <div class="row justify-content-center align-content-center text-center">
        <div class="col-md-5">
            <h1>Admin Interface</h1>
            <p class="mt-3 mb-4"> Add an new Tag </p>                        
        </div>
    </div>
</div>
<%= render 'form' %>