config/routes.rb
Rails.application.routes.draw do
  root  "tasks#index"
  resources :tasks 
  resources :users, only:  %i[new create show]
  resources :sessions, only: %i[new create destroy]

  namespace :admin do
    resources :users
    resources :tags
  end
end

app/models/user.rb
class User < ApplicationRecord 
    before_update :destroy_admin
    before_create :destroy_admin
    before_destroy :check_admin
    validates :name, presence:true, length: {minimum:3, maximum:30}
    validates :email, presence:true, length: { maximum:255 }, 
                format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
                uniqueness: true      
    validates :password, presence: true, length: { minimum:8 }, unless: Proc.new { |user| user.password.blank? }
    has_secure_password
    has_many :tasks, dependent: :destroy

    private
    def destroy_admin
        if self.admin 
            User.update_all(admin: 0)
        end
    end

    def check_admin
        if self.admin 
            throw(:abort)
        end
    end
    
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update, :destroy]
  before_action :check_admin
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to admin_users_path, notice: "New user create with success"
    else  
        render :new
    end
  end
  def show
  end
  def edit
  end
  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "Update informations with success"
    else
      render :edit
    end
  end
  def destroy
    @user.destroy
    if @user.admin
      redirect_to admin_users_path, notice: "You can't delete the last admin"
    else
      redirect_to admin_users_path, notice: "User delete with success"
    end  
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
  def set_user
    @user = User.find(params[:id])
  end
  def check_admin
    unless current_user.admin
        redirect_to tasks_path, notice: "Your are not authorized to see this page"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required
  before_action :set_user, only: [:show]
  def new
    if session[:user_id].present?
      redirect_to tasks_path, notice: "Please stay on tasks page"
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(users_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_path, notice: "Welcome #{@user.name}"
    else  
      render :new
    end
  end
  def show
    if current_user.id != @user.id
      redirect_to tasks_path
    end
  end
  private
  def users_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show pt-2 pb-2 text-center">
        <% @user.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>
<div class="container-fluid pt-5 pb-2" id='intro'>
    <div class="row justify-content-center align-content-center text-center">
        <div class="col-md-5">
            <h1>Admin Interface</h1>
            <p class="mt-4 mb-4"> Update user Informations </p>                        
        </div>
    </div>
</div>
<div class="container">
    <div class="row justify-content-center align-content-center">
        <div class= "col-lg-5 col-md-8 col-sm-12 col-xl-4">
            <div class="card p-3 mb-3 bg-white" >
                <div class="card-header pl-4 pb-0 text-center" style="border: none; background-color:white;">
                    <%= image_tag "myTask.png", height: 80, width: 80 %>         
                </div>
                <div class="card-body">
                    <%= form_with(model: @user, local: true, url: admin_user_path) do |form| %>
                        <div class="form-group">
                            <%= form.text_field :email, class: "form-control bg-light small", required: true, placeholder: "Email address" %>
                        </div>
                        <div class="form-group">
                            <%= form.text_field :name, class: "form-control bg-light", required: true, placeholder: "Name" %>
                        </div>
                        <div class="form-group">
                            <%= form.label :admin, "Rule"%>
                            <%= form.select :admin, options_for_select([["General User",0], ["Admin", 1]], selected: @user.admin)%>
                        </div>
                        <div class="row justify-content-center mb-3 mt-4">
                            <div class="col-md-12 text-center">
                                <%= form.submit "Save", class:"btn btn-primary font-weight-bold pl-5 pr-5" %>
                            </div>
                        </div>
                    <% end %>
                </div>  
            </div>
        </div> 
    </div>
</div>
<div class="d-block text-center">
    <p><%= link_to "Back", admin_users_path, class: "btn btn-primary text-white" %></p>
</div>

app/views/admin/users/index.html.erb
<div class="container-fluid pt-5 pb-2" id='intro'>
    <div class="row justify-content-center align-content-center text-center">
        <div class="col-md-5">
            <h1>Admin Interface</h1>
            <p class="mt-4 mb-4"> Manage all users here. With this page you can have a global view of your application users. You can delete, edit user profile like you want</p>                        
            <p><%= link_to "See your tags Here", admin_tags_path, class: "btn btn-primary text-white" %></p>
        </div>
    </div>
</div>

<div class="d-block pl-3 mt-3">
    <p><%= link_to "New User", new_admin_user_path, class: "btn btn-primary new_btn text-white" %></p>
</div>
<div class="container-fluid mt-2 mb-3">
    <div class="row justify-content-center align-content-center">
        <div class="col-md-12">
            <table class="table table-sm">
                <thead>
                    <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>                   
                    <th scope="col">Registered Date</th>
                    <th scope="col">Rule</th>
                    <th scope="col">Tasks Number</th>                    
                    </tr>
                </thead>
                <tbody>
                    <% if @users.count > 0%>
                        <% @users.each do |user| %>
                            <tr>
                                <th scope="row" class="task_row"><%=user.name%></th>
                                <td><%=user.email%></td>
                                <td><%=user.created_at%></td>
                                <td><%= user.admin ? "Admin" : "General User" %></td>
                                <td><%=user.tasks.count %></td>
                                <td><%= link_to 'Show' , admin_user_path(user.id), class: "show-link"  %></td>
                                <td><%= link_to 'Edit' , edit_admin_user_path(user.id), class: "edit-link"  %></td>
                                <td><%= link_to 'Delete' ,admin_user_path(user.id), method: :delete , data: { confirm: 'Are you sure to delete this user'}, class:"delete-link" %></td>
                            </tr>
                        <%end%>       
                    <%end%>   
                </tbody>
            </table>
            <% if @users.count == 0 %>                   
                <p class="text-center font-weight-bold"> Nothing to show yet.</p>
                <p class="text-center"> If you don't have any user, please create your first task</p>
                <div class="d-block text-center">
                    <p><%= link_to "Create First Task", new_admin_user_path, class: "btn btn-primary text-white" %></p>
                </div>
            <%end%>  
                                   
        </div>
    </div>
</div>


app/views/admin/users/new.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show pt-2 pb-2 text-center">
        <% @user.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
        <% end %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>
<div class="container-fluid pt-3 pb-2" id='intro'>
    <div class="row justify-content-center align-content-center text-center">
        <div class="col-md-5">
            <h1>Admin Interface</h1>
            <p class="mt-3 mb-4"> Add an new user </p>                        
        </div>
    </div>
</div>
<div class="container">
    <div class="row justify-content-center align-content-center">
        <div class= "col-lg-5 col-md-8 col-sm-12 col-xl-4">
            <div class="card p-3 mb-3 bg-white" >
                <div class="card-header pl-4 pb-0 text-center" style="border: none; background-color:white;">
                    <%= image_tag "myTask.png", height: 80, width: 80 %>         
                </div>
                <div class="card-body">
                    <%= form_with(model: @user, local: true, url: admin_users_path) do |form| %>
                        <div class="form-group">
                            <%= form.text_field :email, class: "form-control bg-light small", required: true, placeholder: "Email address" %>
                        </div>
                        <div class="form-group">
                            <%= form.text_field :name, class: "form-control bg-light", required: true, placeholder: "Name" %>
                        </div>
                        <div class="form-group">
                            <%= form.label :admin, "Rule"%>
                            <%= form.select :admin, [["General User",0], ["Admin", 1]], class: "form-control bg-light"%>
                        </div>
                        <div class="form-group">
                            <%= form.password_field :password, class: "form-control bg-light", required: true, placeholder: "Password" %>
                        </div>
                        <div class="form-group">
                            <%= form.password_field :password_confirmation, class: "form-control bg-light", required: true, placeholder: "Confirm password" %>
                        </div>
                        <div class="row justify-content-center mb-3 mt-4">
                            <div class="col-md-12 text-center">
                                <%= form.submit "Create Account", class:"btn btn-primary font-weight-bold pl-5 pr-5" %>
                            </div>
                        </div>
                    <% end %>
                </div>  
            </div>
        </div> 
    </div>
</div>
<div class="d-block text-center">
    <p><%= link_to "Back", admin_users_path, class: "btn btn-primary text-white" %></p>
</div>

app/views/admin/users/show.html.erb
<h3 class= "mb-4 text-center mt-4"> User Details Informations</h3>

<div class="container-fluid mt-2">
    <div class="row justify-content-center align-content-center">
        <div class= "col-md-4 ">
            <div class="card bg-light mb-3" style="max-width: 100rem;">
                <div class="card-header font-weight-bold text-center"><%= @user.name %></div>
                <div class="card-body">
                    <p class="card-text text-justify">Name : <%= @user.name %> </p>
                    <p class="card-text text-justify">Email : <%= @user.email %></p>
                    <p class="card-text text-justify">Rule : <%= @user.admin ? "Admin" : "General User" %></p>
                    <p class="card-text text-justify">Task Number : <%= @user.tasks.count %> </p>
                </div>
            </div>
        </div> 
    </div>
</div> 

<div class="d-block text-center">
    <p><%= link_to "Back", admin_users_path, class: "btn btn-primary text-white" %></p>
</div>
