config/routes.rb
Rails.application.routes.draw do
  root  "tasks#index"
  resources :tasks 
  resources :users, only:  %i[new create show]
  resources :sessions, only: %i[new create destroy]

  namespace :admin do
    resources :users
    resources :tags
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light navbar-expand-lg bg-light">      
      <a class="navbar-brand font-weight-bold d-block" href="/tasks" id="top-link">
        <%= image_tag "myTask.png", width: 35, height: 35 , class: "d-inline-block align-top" %>
        My Task 
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active"> 
              <% if logged_in? %>
                <%= link_to "All Task List", tasks_path, class: "home_link" %> 
                <% if current_user.admin %>
                  <%= link_to "Admin Page", admin_users_path, class: "pl-3 home_link" %> 
                <% end %> 
              <% end %>
          </li>
        </ul>
        <% if logged_in? %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown pr-5">
                <%= link_to 'Profile', user_path(current_user.id) %>                 
                  
                <%= link_to 'Logout', session_path(current_user.id), method: :delete, class: "" %>
                <% if current_user.admin %>
                  Admin
                <% end %>
                <%= current_user.name %> 
            </li>
          </ul>
        <% end %>
      </div>  
    </nav>
    <% flash.each do |key, value| %>
        <%= content_tag(:div, class: "alert alert-#{key} alert-dismissible fade show pt-2 pb-2", role: "alert") do %>
          <p class="text-center font-weight-bold"><%= value %> </p>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        <% end %>  
    <% end %>
    <%= yield %>
  </body>
</html>